name: JMeter Load Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install JMeter (Latest)
        run: |
          JMETER_VERSION=5.6.3
          wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-${JMETER_VERSION}.tgz
          tar -xzf apache-jmeter-${JMETER_VERSION}.tgz
          echo "$PWD/apache-jmeter-${JMETER_VERSION}/bin" >> $GITHUB_PATH

      - name: Run JMeter Test
        run: |
          jmeter -n \
            -t jmeter/jsonplaceholder-test.jmx \
            -l results.jtl \
            -e -o report

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-report
          path: report
